### ISSUE TITLE
Json Organization

### ISSUE THREAD

**Issue by hariiprasad** [yuvaraj1997/Flash-Attendance-System#1]
Hii..Thanks for your awesome code. May i know the Example of your firebase realtime database ? .

**Comment by yuvaraj1997** [comment]
> Hii..Thanks for your awesome code. May i know the Example of your firebase realtime database ? .

Admin 
email = admin@gmail.com
pass = test1234

Lecturer 
email = moamin@gmail.com
pass = test1234

Student 
email = vishnu@gmail.com
pass = test1234


[json.docx](https://github.com/yuvaraj1997/Flash-Attendance-System/files/2863367/json.docx)

**Comment by hariiprasad** [comment]
@yuvaraj1997 thanks bro will check it🤘
